import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Buttons from "@/component/Buttons";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Finnova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}`}
      >
        <Navbar />
        {children}
        <Buttons />
      </body>
    </html>
  );
}
